version: "3"

services:
  todo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-server
    ports:
      - "3000:3000"
    volumes:
      - "./:/todo-server"
    command: ["air"]

  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
